-- Event to send position and screenshot to Discord
RegisterNetEvent('sendPositionToWebhook')
AddEventHandler('sendPositionToWebhook', function(playerId, pos, imageURL)
    -- Prepare the data for Discord
    local embed = {
        {
            title = "Player",
            description = string.format("Player ID: **%d**", playerId) .. "\n" .. string.format("Position: **Vector3(%.2f, %.2f, %.2f)**", pos.x, pos.y, pos.z),
            color = 16777215, -- Blue color
            image = { url = imageURL },
            footer = { text = "Generated by empire networks logging" }
        }
    }

    -- Send the embed to Discord
    PerformHttpRequest(Config.WebhookURL, function(err, text, headers) end, 'POST', json.encode({ username = "Position Bot", embeds = embed }), { ['Content-Type'] = 'application/json' })
end)